REPORT ZSAMIKSHA_SMARTFORM.
TABLES: ZEMPLOYEE,BNKA,VBAP.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-000.
  SELECT-OPTIONS: N_EMPID FOR ZEMPLOYEE-EMPID.

 SELECTION-SCREEN: END OF BLOCK B1.

 DATA:
 BEGIN OF WA,
 EMPID TYPE ZEMPID,
 EMPNAME TYPE ZEMPNAME,
 MOBILE TYPE ZMOBILE,
 SALARY TYPE ZSAL,
 END OF WA,

 BEGIN OF WA1,
 BANKS TYPE BANKS,
 BANKL TYPE BANKK,
 ERDAT TYPE ERDAT_BF,
 END OF WA1.

DATA : CAT TYPE RS38L_FNAM,
      ITV TYPE TABLE OF ZVBAPSTR,
      WAV TYPE ZVBAPSTR.

SELECT SINGLE EMPID EMPNAME MOBILE SALARY
  FROM ZEMPLOYEE INTO WA
  WHERE EMPID IN N_EMPID.

 SELECT POSNR MATNR KWMENG MEINS NETPR UP TO 5 ROWS
  FROM VBAP INTO CORRESPONDING FIELDS OF TABLE ITV.

  SELECT SINGLE BANKS BANKL ERDAT
    FROM BNKA INTO WA1.

CALL FUNCTION 'SSF_FUNCTION_MODULE_NAME'
EXPORTING
      FORMNAME                 = 'ZFORM_S'
IMPORTING
  FM_NAME = CAT.



CALL FUNCTION CAT
EXPORTING

        EMPID                      = WA-EMPID
        EMPNAME                    = WA-EMPNAME
        MOBILE                     = WA-MOBILE
        SALARY                     = WA-SALARY
        BANKS                      = WA1-BANKS
        BANKL                      = WA1-BANKL
        ERDAT                      = WA1-ERDAT

      TABLES
        ITV                        = ITV.
