REPORT ZMSG1PROGRAM.

"MESSAGE S000(ZMSG1).
"TO GIVE NORMAL POP UP OF MESSAGE BY USING MESSAGE CLASS NAME SHOW MESSAGE IN BAR

"OR
"MESSAGE I000(ZMSG1).
"SHOW IN WINDOWS POP UP BAR

MESSAGE W000(ZMSG1).
