REPORT ZCBS_SAMIKSHA2 NO STANDARD PAGE HEADING.

TABLES: KNA1 , VBAK.
SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-000.
      SELECT-OPTIONS TTT FOR KNA1-KUNNR.
SELECTION-SCREEN: END OF BLOCK B1.

TYPES : BEGIN OF TY_STR,
        KUNNR TYPE KUNNR,
        VBELN TYPE VBELN_VA,
        ERDAT TYPE ERDAT,
        NETWR TYPE NETWR_AK,
        END OF TY_STR.

DATA: IT TYPE TABLE OF TY_STR,
       WA TYPE TY_STR.

SELECT A~KUNNR B~VBELN B~ERDAT B~NETWR
INTO TABLE IT
FROM KNA1 AS A INNER JOIN VBAK AS B
ON  A~KUNNR = B~KUNNR
WHERE A~KUNNR IN TTT.

LOOP AT IT INTO WA.

AT FIRST.
   WRITE:/70 'CONTROL BREAK STATEMENT PROGRAM' COLOR 3.
ENDAT.
   
AT NEW KUNNR.
     WRITE:/ 'THE CUSTOMER NUBER IS =', WA-KUNNR COLOR 7.
ENDAT.

WRITE:/20 WA-VBELN,
       40 WA-ERDAT,
       60 WA-NETWR.

AT END OF KUNNR.
  SUM.
  WRITE:/ 'THE SUB TOTAL IS ', 60 WA-NETWR COLOR 3.
  ULINE.
ENDAT.

AT LAST.
  SUM.
  WRITE:/ 'THE GRAND TOTAL IS ', 60 WA-NETWR COLOR 5.
  ULINE.
ENDAT.

ENDLOOP.
