REPORT ZCBS_SAMIKSHA NO STANDARD PAGE HEADING.

TABLES: VBAK, KNA1.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-000.
  SELECT-OPTIONS: TTT FOR KNA1-KUNNR.
  SELECTION-SCREEN: END OF  BLOCK B1.
TYPES:
BEGIN OF TY_STR,
VBELN TYPE VBELN_VA,
ERZET TYPE ERZET,
ANGDT TYPE ANGDT_v,
KUNNR TYPE KUNNR,
PSTLZ TYPE PSTLZ,
END OF TY_STR.

DATA: IT TYPE TABLE OF TY_STR,
      WA TYPE TY_STR.

SELECT A~VBELN A~ERZET A~ANGDT B~KUNNR B~PSTLZ
INTO TABLE IT
FROM VBAK AS A INNER JOIN KNA1 AS B
ON A~KUNNR = B~KUNNR
WHERE A~KUNNR IN TTT.

LOOP AT IT INTO WA.
  AT FIRST.

    WRITE:/ 'CONTROL BREAK STATEMENT' COLOR 2.

  ENDAT.

  AT NEW KUNNR.

    WRITE:/ 'CUSTOMER ID: ',WA-KUNNR COLOR 3.

  ENDAT.

  AT END OF KUNNR.
    SUM.
    WRITE:/ ' QUOTATION IS VALID FROM SUM: ',WA-ANGDT COLOR 4.

  ENDAT.

  AT LAST.
    SUM.
    WRITE:/ 'QUATION VALID FROM GRAND TOTAL IS: ',WA-ANGDT COLOR 5.

   ENDAT.

  ENDLOOP.
