TABLES : LFA1, EKKO, EKPO.

TYPE-POOLS SLIS."TO DECLARE THE TYPE GROUP.

SELECTION-SCREEN : BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
  SELECT-OPTIONS: S_LIFNR FOR LFA1-LIFNR.
SELECTION-SCREEN:END OF BLOCK B1.

TYPES:
BEGIN OF TY_STR1,
  LIFNR TYPE LIFNR,
  NAME1 TYPE NAME1_GP,
  ORT01 TYPE ORT01_GP,
  PSTLZ TYPE PSTLZ,
  STRAS TYPE STRAS_GP,
END OF TY_STR1,

BEGIN OF TY_STR2,
  EBELN TYPE EBELN,
  AEDAT TYPE ERDAT,
  ZTERM TYPE DZTERM,
  LIFNR TYPE ELIFN,
END OF TY_STR2,

BEGIN OF TY_STR3,
  EBELP TYPE EBELP,
  MATNR TYPE MATNR,
  MENGE TYPE BSTMG,
  MEINS TYPE BSTME,
  NETPR TYPE BPREI,
  EBELN TYPE EBELN,
END OF TY_STR3.

DATA: IT1 TYPE TABLE OF TY_STR1,
      IT2 TYPE TABLE OF TY_STR2,
      IT3 TYPE TABLE OF TY_STR3.

DATA:
      WAFC1 TYPE SLIS_FIELDCAT_ALV,
      ITFC1 TYPE SLIS_T_FIELDCAT_ALV,

      WAFC2 TYPE SLIS_FIELDCAT_ALV,
      ITFC2 TYPE SLIS_T_FIELDCAT_ALV,

      WAFC3 TYPE SLIS_FIELDCAT_ALV,
      ITFC3 TYPE SLIS_T_FIELDCAT_ALV,

      WAE TYPE SLIS_ALV_EVENT,
      ITE TYPE SLIS_T_EVENT.

DATA: V_LIFNR TYPE LIFNR,
      V_EBELN TYPE EBELN.
