FORM GETDATA .
SELECT LIFNR NAME1 ORT01 PSTLZ STRAS
  FROM LFA1 INTO TABLE IT1
  WHERE LIFNR IN S_LIFNR.
ENDFORM.

FORM FIELDCAT .
CLEAR WAFC1.
WAFC1-COL_POS = 1.
WAFC1-FIELDNAME = 'LIFNR'.
WAFC1-TABNAME = 'IT1'.
WAFC1-SELTEXT_M = 'LIFNR'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC1 TO ITFC1.

CLEAR WAFC1.
WAFC1-COL_POS = 2.
WAFC1-FIELDNAME = 'NAME1'.
WAFC1-TABNAME = 'IT1'.
WAFC1-SELTEXT_M = 'NAME'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC1 TO ITFC1.

CLEAR WAFC1.
WAFC1-COL_POS = 3.
WAFC1-FIELDNAME = 'ORT01'.
WAFC1-TABNAME = 'IT1'.
WAFC1-SELTEXT_M = 'CITY'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC1 TO ITFC1.

CLEAR WAFC1.
WAFC1-COL_POS = 4.
WAFC1-FIELDNAME = 'PSTLZ'.
WAFC1-TABNAME = 'IT1'.
WAFC1-SELTEXT_M = 'POSTAL'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC1 TO ITFC1.

CLEAR WAFC1.
WAFC1-COL_POS = 5.
WAFC1-FIELDNAME = 'STRAS'.
WAFC1-TABNAME = 'IT1'.
WAFC1-SELTEXT_M = 'STREET'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC1 TO ITFC1.

" EKKO

CLEAR WAFC2.
WAFC1-COL_POS = 1.
WAFC1-FIELDNAME = 'EBELN'.
WAFC1-TABNAME = 'IT2'.
WAFC1-SELTEXT_M = 'EBELN'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC2 TO ITFC2.

CLEAR WAFC2.
WAFC1-COL_POS = 2.
WAFC1-FIELDNAME = 'AEDAT'.
WAFC1-TABNAME = 'IT2'.
WAFC1-SELTEXT_M = 'AEDAT'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC2 TO ITFC2.

CLEAR WAFC2.
WAFC1-COL_POS = 3.
WAFC1-FIELDNAME = 'ZTERM'.
WAFC1-TABNAME = 'IT2'.
WAFC1-SELTEXT_M = 'ZTERM'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC2 TO ITFC2.

CLEAR WAFC2.
WAFC1-COL_POS = 4.
WAFC1-FIELDNAME = 'LIFNR'.
WAFC1-TABNAME = 'IT2'.
WAFC1-SELTEXT_M = 'LIFNR'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC2 TO ITFC2.

" EKPO

CLEAR WAFC3.
WAFC1-COL_POS =  1.
WAFC1-FIELDNAME = 'EBELP'.
WAFC1-TABNAME = 'IT3'.
WAFC1-SELTEXT_M = 'EBELP'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC3 TO ITFC3.

CLEAR WAFC3.
WAFC1-COL_POS =  2.
WAFC1-FIELDNAME = 'MATNR'.
WAFC1-TABNAME = 'IT3'.
WAFC1-SELTEXT_M = 'MATNR'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC3 TO ITFC3.

CLEAR WAFC3.
WAFC1-COL_POS =  3.
WAFC1-FIELDNAME = 'MENGE'.
WAFC1-TABNAME = 'IT3'.
WAFC1-SELTEXT_M = 'MENGE'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC3 TO ITFC3.

CLEAR WAFC3.
WAFC1-COL_POS =  4.
WAFC1-FIELDNAME = 'MEINS'.
WAFC1-TABNAME = 'IT3'.
WAFC1-SELTEXT_M = 'MEINS'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC3 TO ITFC3.

CLEAR WAFC3.
WAFC1-COL_POS =  5.
WAFC1-FIELDNAME = 'NETPR'.
WAFC1-TABNAME = 'IT3'.
WAFC1-SELTEXT_M = 'NETPR'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC3 TO ITFC3.

CLEAR WAFC3.
WAFC1-COL_POS =  6.
WAFC1-FIELDNAME = 'EBELN'.
WAFC1-TABNAME = 'IT3'.
WAFC1-SELTEXT_M = 'EBELN'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC3 TO ITFC3.

ENDFORM.

FORM EVENT .

CLEAR WAE.
WAE-NAME = 'USER_COMMAND'.
WAE-FORM = 'INTERACTIVE'.
APPEND WAE TO ITE.

CLEAR WAE.
WAE-NAME = 'TOP-OF-PAGE'.
WAE-FORM = 'HEADING'.
APPEND WAE TO ITE.

ENDFORM.

FORM DISPLAY .
CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
EXPORTING

  I_CALLBACK_PROGRAM                = SY-CPROG

 IT_FIELDCAT                       = ITFC1

  IT_EVENTS                         = ITE

  TABLES
    T_OUTTAB                          = IT1.

ENDFORM.

FORM INTERACTIVE USING UCOMM LIKE SY-UCOMM SEL TYPE SLIS_SELFIELD.
 IF SEL-FIELDNAME = 'LIFNR'.
V_LIFNR = SEL-VALUE.
SELECT EBELN AEDAT ZTERM LIFNR
  FROM EKKO INTO TABLE IT2
  WHERE LIFNR = V_LIFNR.

CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
EXPORTING

 I_CALLBACK_PROGRAM                = SY-CPROG
 IT_FIELDCAT                       =  ITFC2
 IT_EVENTS                         = ITE
*
  TABLES
    T_OUTTAB                          = IT2.

ENDIF.

IF SEL-FIELDNAME = 'EBELN'.
V_EBELN = SEL-VALUE.
SELECT EBELP MATNR MENGE MEINS NETPR EBELN
  FROM EKPO INTO TABLE IT3
  WHERE EBELN = V_EBELN.
  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
          EXPORTING
            I_CALLBACK_PROGRAM                =  SY-CPROG
             IT_FIELDCAT                      =  ITFC3
            IT_EVENTS                         =  ITE
           TABLES
             T_OUTTAB                         =  IT3.
 ENDIF.

 IF SEL-FIELDNAME = 'MATNR'.
   CALL TRANSACTION 'SE11' AND SKIP FIRST SCREEN.
 ENDIF.
ENDFORM.

FORM HEADING.
  DATA: STR TYPE STRING.
  DATA: WAL TYPE SLIS_LISTHEADER,
        ITL TYPE SLIS_T_LISTHEADER.

  CLEAR WAL.
  WAL-TYP = 'H'.
  WAL-INFO = 'CSMSS PVT .LTD'.
  APPEND WAL TO ITL.
  ENDFORM.
