FORM INIT .
N_PERNR-SIGN = 'I'.
N_PERNR-OPTION = 'BT'.
N_PERNR-LOW = 'E0001'.
N_PERNR-HIGH = 'E0005'.
APPEND N_PERNR.
ENDFORM.
  
FORM VAL .
IF N_PERNR-LOW < 'E0001' OR N_PERNR-HIGH > 'E0005'.
  MESSAGE 'ENTER VALLIDATE NO.' TYPE 'E'.
ENDIF.
ENDFORM.
  
FORM GET .
SELECT MANDT PERNR FIRSTNAME LASTNAME ORGUNT
  FROM ZPA0001 INTO TABLE IT
  WHERE PERNR IN N_PERNR.
ENDFORM.
  
FORM DIS .
WRITE:/ 'MANDT' , 10 'PERNR' , 20 'FIRSTNAME',35 'LASTNAME',
50 'ORGUNIT'.
ULINE.
  
LOOP AT IT INTO WA.
  WRITE:/
  WA-MANDT,
  15 WA-PERNR,
  12 WA-FIRSTNAME,
  35 WA-LASTNAME,
  60 WA-ORGUNT.
ENDLOOP.
ENDFORM.
