TABLES: ZPA0001.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-000.
  SELECT-OPTIONS: N_PERNR FOR ZPA0001-PERNR.
SELECTION-SCREEN: END OF BLOCK B1.

TYPES: BEGIN OF TY_STR1,
  MANDT TYPE MANDT,
  PERNR TYPE ZPERNR1,
  FIRSTNAME TYPE ZFNAME11,
  LASTNAME TYPE ZLNAME11,
  ORGUNT TYPE ZDEPT11,
END OF TY_STR1.

DATA:
      IT TYPE TABLE OF TY_STR1,
      WA TYPE TY_STR1.
