REPORT ZSAMIKSHA_CLASSICAL.

INCLUDE ZCLASSICAL_TOP1.
INCLUDE ZCLASSICAL_FORM1.

INITIALIZATION.
PERFORM INIT.

AT SELECTION-SCREEN ON N_PERNR.
PERFORM VAL.

START-OF-SELECTION.
PERFORM GET.
END-OF-SELECTION.
PERFORM DIS.

TOP-OF-PAGE.
WRITE:/70 'MANDT' ,SY-MANDT COLOR 2,
'USER NAME', SY-UNAME COLOR 3,
'DATE',SY-DATUM COLOR 4,
'TIME', SY-UZEIT COLOR 5.
ULINE.

END-OF-PAGE.
WRITE:/70 'FOOTER' COLOR 3.
