REPORT ZSTRING_OPERATION NO STANDARD PAGE HEADING.
DATA :
STR1 TYPE STRING," DEFINING THAT THE DATA IS IN STRING FORMAT
STR2 TYPE STRING.

STR1 = 'GOOD MORNING AURANGABAD...!'."TEXT STORED IN STRING 1
STR2 = 'GOOD NIGHT MUMBAI...!'.
WRITE: / STR1." PRINTED THE STRING1

TRANSLATE STR1 TO LOWER CASE."CHANGED THE UPPERCASE INTO LOWERCASE.
WRITE: / STR1.

DATA: COUNT TYPE I.
COUNT = STRLEN( STR1 )."COUNTED THE STTRING LENGTH IN INTEGER FORMAT
WRITE:/ COUNT.

CONDENSE  STR1 NO-GAPS."CONDENSE HELPS TO REMOVE UNWANTED SPACE INSIDE TEXT.
WRITE:/ COUNT.

CONCATENATE STR1 STR2 INTO STR1 SEPARATED BY ' '." CONCATENATE USED TO COMBINE TWO STRING IN SINGLE STRING.
WRITE: / STR1.

REPLACE STR1 WITH STR2 INTO STR1." REPLACING STRING 1 WITH STRING 2 TEXT.
WRITE:/ STR1.

SEARCH STR1 FOR STR2."serching common words inside given text
IF SY-SUBRC = 0." if text present then print if text and if not present then print else text
  WRITE:/ 'THE STRING IS PRESENT'.
ELSE.
  WRITE:/ 'NOT FOUND'.
ENDIF.

SPLIT STR1 AT ' ' INTO STR1 STR2."start to print from given chracter or space.
WRITE: / STR1.
WRITE: / STR2.
