REPORT ZCLASSICAL_ALV.

TABLES : LFA1,EKKO.

SELECTION-SCREEN : BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-000.
SELECT-OPTIONS : S_LIFNR FOR LFA1-LIFNR,
                 S_AEDAT FOR EKKO-AEDAT.
SELECTION-SCREEN : END OF BLOCK B1 .

SELECTION-SCREEN : BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-000.
PARAMETERS : IT1TABLE RADIOBUTTON GROUP ST,
              IT2TABLE RADIOBUTTON GROUP ST.
SELECTION-SCREEN : END OF BLOCK B2 .

DATA : IT1 TYPE TABLE OF ZLFA1_TABLE,
       WA1 TYPE           ZLFA1_TABLE,

       IT2 TYPE TABLE OF ZEKKO_TABLE,
       WA2 TYPE           ZEKKO_TABLE.

       SELECT LIFNR NAME1 ORT01 PSTLZ
       FROM LFA1 INTO TABLE IT1
       WHERE LIFNR IN S_LIFNR.

       IF IT1[] IS NOT INITIAL.
       SELECT EBELN AEDAT ZTERM LIFNR
       FROM EKKO INTO TABLE IT2
       FOR ALL ENTRIES IN IT2
       WHERE LIFNR = IT2-LIFNR
       AND AEDAT IN S_AEDAT.
       ENDIF.

       IF IT1TABLE = 'X'.

       CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
        EXPORTING

         I_CALLBACK_PROGRAM                = 'SY-CPROG'

         I_STRUCTURE_NAME                  = 'ZLFA1_TABLE'

         TABLES
           T_OUTTAB                        = IT1.

       ENDIF.

   IF IT2TABLE = 'X'.
 
   CALL FUNCTION 'REUSE_ALV_LIST_DISPLAY'
     EXPORTING

      I_CALLBACK_PROGRAM             = 'SY-CPROG '

      I_STRUCTURE_NAME               = 'ZEKKO_TABLE'

       TABLES
         T_OUTTAB                       = IT2.

     ENDIF.
