FORM GETDATA .
SELECT A~MANDT A~PERNR A~FIRSTNAME A~LASTNAME A~ORGUNT
B~PLANS B~JOBTITLE B~BEGDA INTO CORRESPONDING FIELDS OF TABLE IT1 FROM ZPA0001 AS A
INNER JOIN ZPA0002 AS B ON A~PERNR = B~PERNR.
ENDFORM.

FORM FIELDCAT .
CLEAR WAFC1.
WAFC1-COL_POS = 1.
WAFC1-FIELDNAME = 'MANDT'.
WAFC1-TABNAME = 'IT1'.
WAFC1-SELTEXT_M = 'MANDT'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC1 TO ITFC1.

CLEAR WAFC1.
WAFC1-COL_POS = 2.
WAFC1-FIELDNAME = 'PERNR'.
WAFC1-TABNAME = 'IT1'.
WAFC1-SELTEXT_M = 'PERNR'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC1 TO ITFC1.

CLEAR WAFC1.
WAFC1-COL_POS = 3.
WAFC1-FIELDNAME = 'FIRSTNAME'.
WAFC1-TABNAME = 'IT1'.
WAFC1-SELTEXT_M = 'FIRSTNAME'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC1 TO ITFC1.

CLEAR WAFC1.
WAFC1-COL_POS = 4 .
WAFC1-FIELDNAME = 'LASTNAME'.
WAFC1-TABNAME = 'IT1'.
WAFC1-SELTEXT_M = 'LASTNAME'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC1 TO ITFC1.

CLEAR WAFC1.
WAFC1-COL_POS = 5.
WAFC1-FIELDNAME ='ORGUNT'.
WAFC1-TABNAME = 'IT1'.
WAFC1-SELTEXT_M = 'ORGUNT'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC1 TO ITFC1.

CLEAR WAFC2.
WAFC1-COL_POS = 1 .
WAFC1-FIELDNAME = 'MANDT'.
WAFC1-TABNAME = 'IT2'.
WAFC1-SELTEXT_M = 'MANDT'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC2 TO ITFC2.

CLEAR WAFC2.
WAFC1-COL_POS = 2.
WAFC1-FIELDNAME = 'PERNR'.
WAFC1-TABNAME = 'IT2'.
WAFC1-SELTEXT_M = 'PERNR'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC2 TO ITFC2.

CLEAR WAFC2.
WAFC1-COL_POS = 3.
WAFC1-FIELDNAME = 'PLANS'.
WAFC1-TABNAME = 'IT2'.
WAFC1-SELTEXT_M = 'PLANS'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC2 TO ITFC2.

CLEAR WAFC2.
WAFC1-COL_POS = 4.
WAFC1-FIELDNAME = 'JOBTITLE'.
WAFC1-TABNAME = 'IT2'.
WAFC1-SELTEXT_M = 'JOBTITLE'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC2 TO ITFC2.

CLEAR WAFC2.
WAFC1-COL_POS = 5.
WAFC1-FIELDNAME = 'BEGDA'.
WAFC1-TABNAME = 'IT2'.
WAFC1-SELTEXT_M = 'BEGDA'.
WAFC1-OUTPUTLEN = 15.
APPEND WAFC2 TO ITFC2.
ENDFORM.

FORM EVENT .
CLEAR WAE.
WAE-NAME = 'USER COMMAND'.
WAE-FORM = 'INTERACTIVE'.
APPEND WAE TO ITE.

CLEAR WAE.
WAE-NAME = 'TOP_OF_PAGE'.
WAE-FORM = 'HEADING'.
APPEND WAE TO ITE.
ENDFORM.

FORM DISPLAY .
CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
EXPORTING
 I_CALLBACK_PROGRAM                = SY-CPROG

 IT_FIELDCAT                       = ITFC1

 IT_EVENTS                         = ITE

  TABLES
 T_OUTTAB                          = IT1.

ENDFORM.

FORM INTERACTIVE USING UCOMM LIKE SY-UCOMM SEL TYPE SLIS_SELFIELD.
IF SEL-FIELDNAME = 'PERNR'.
V_PERNR = SEL-VALUE.

SELECT PERNR PLANS JOBTITLE BEGDA
FROM ZPA0002 INTO TABLE IT2
WHERE PERNR = V_PERNR.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
          EXPORTING
            I_CALLBACK_PROGRAM                =  SY-CPROG
             IT_FIELDCAT                      =  ITFC2
            IT_EVENTS                         =  ITE
           TABLES
             T_OUTTAB                         =  IT2.
ENDIF.
ENDFORM.
FORM HEADING.

DATA:STR TYPE STRING.
DATA: WAL TYPE SLIS_LISTHEADER,
      ITL TYPE SLIS_T_LISTHEADER.

 CLEAR WAL.
 WAL-TYP = 'H'.
 WAL-INFO = 'TEST 2'.
 APPEND WAL TO ITL.

CLEAR WAL.
WAL-TYP = 'S'.
WAL-KEY = 'USERNAME'.
WAL-INFO = SY-UNAME.
APPEND WAL TO ITL.

WAL-TYP = 'S'.
WAL-KEY = 'DATE'.
CONCATENATE SY-DATUM+6(2) SY-DATUM+4(2) SY-DATUM+0(4) INTO STR SEPARATED BY '.'.
WAL-INFO = STR.
APPEND WAL TO ITL.

CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
  EXPORTING
 IT_LIST_COMMENTARY       = ITL
 I_LOGO                   = 'SAPP'

          .

 ENDFORM.
