TABLES : ZPA0001, ZPA0002.

TYPE-POOLS : SLIS.
SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-000.
  SELECT-OPTIONS: N_PERNR FOR ZPA0001-PERNR.
  SELECTION-SCREEN: END OF BLOCK B1.

TYPES: BEGIN OF TY_STR1,
  MANDT TYPE MANDT,
  PERNR TYPE ZPERNR1,
  FIRSTNAME TYPE ZFNAME11,
  LASTNAME TYPE ZLNAME11,
  ORGUNT TYPE ZDEPT11,
END OF TY_STR1,

BEGIN OF TY_STR2,
  MANDT TYPE MANDT,
  PERNR TYPE ZPERNR1,
  PLANS TYPE ZPID,
  JOBTITLE TYPE ZJTITLE,
  BEGDA TYPE ZSDATE,
  END OF TY_STR2.

DATA:
      IT1 TYPE TABLE OF TY_STR1,
      IT2 TYPE TABLE OF TY_STR2.

DATA:
      WAFC1 TYPE SLIS_FIELDCAT_ALV,
      ITFC1 TYPE SLIS_T_FIELDCAT_ALV,

      WAFC2 TYPE SLIS_FIELDCAT_ALV,
      ITFC2 TYPE SLIS_T_FIELDCAT_ALV,

      WAE TYPE SLIS_ALV_EVENT,
      ITE TYPE SLIS_T_EVENT.

      DATA: V_PERNR TYPE PERNR.
