REPORT ZSAMIKSHA_INTERACTIVEALV.

INCLUDE ZINTERACTIVEALV1_TOP.
INCLUDE ZINTERACTIVEALV1_FORM.

START-OF-SELECTION.
PERFORM GETDATA.
PERFORM FIELDCAT.
PERFORM EVENT.
PERFORM DISPLAY.

TOP-OF-PAGE.
WRITE:/70 'MANDT' ,SY-MANDT COLOR 2,
'USER NAME', SY-UNAME COLOR 3,
'DATE',SY-DATUM COLOR 4,
'TIME', SY-UZEIT COLOR 5.
ULINE.

END-OF-PAGE.
WRITE:/70 'FOOTER' COLOR 3.
