TABLES: ZPA0001,ZPA20111.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-000.
  SELECT-OPTIONS: N_PERNR FOR ZPA0001-PERNR.
SELECTION-SCREEN: END OF BLOCK B1.

TYPES: BEGIN OF TY_STR1,
  MANDT TYPE MANDT,
  PERNR TYPE ZPERNR1,
  FIRSTNAME TYPE ZFNAME11,
  LASTNAME TYPE ZLNAME11,
  ORGUNT TYPE ZDEPT11,
END OF TY_STR1,

BEGIN OF TY_STR2,
  MANDT TYPE MANDT,
  ATTID TYPE ZAID,
  PERNR TYPE ZPERNR1,
  ATTDATE TYPE ZATDATE,
  STATUS TYPE ZST1,
  REMARKS TYPE ZREMARK,
END OF TY_STR2.

DATA:
      IT1 TYPE TABLE OF TY_STR1,
      WA1 TYPE TY_STR1,
      IT2 TYPE TABLE OF TY_STR2,
      WA2 TYPE TY_STR2.
