FORM GETDATA .
SELECT * FROM ZPA0001 INTO CORRESPONDING FIELDS OF TABLE IT1
WHERE PERNR IN N_PERNR.
ENDFORM.

FORM DISPLAY .
  WRITE:/ 'MANDT' COLOR 3,
         10 'PERNR'COLOR 3,
         40 'FIRSTNAME' COLOR 3,
         60'LASTNAME' COLOR 3 ,
         80'ORGUNT'COLOR 3. ULINE.
LOOP AT IT1 INTO WA1.
  WRITE:/ WA1-PERNR HOTSPOT,
        10 WA1-MANDT,
        40 WA1-FIRSTNAME,
        60 WA1-LASTNAME ,
        80 WA1-ORGUNT .
HIDE WA1-PERNR.
ENDLOOP.
ENDFORM.

AT LINE-SELECTION.
CASE SY-LSIND.
WHEN 1.
  SELECT MANDT ATTID PERNR ATTDATE STATUS REMARKS
  FROM ZPA20111 INTO TABLE IT2
  WHERE PERNR = WA1-PERNR.
         
WRITE:/  'MANDT' COLOR 3,
        20'PERNR' COLOR 3,
        35 'ATTID' COLOR 3,
        45 'STATUS' COLOR 3,
        65 'REMARKS'COLOR 3.

LOOP AT IT2 INTO WA2.
   WRITE:/ WA2-MANDT,
        20 WA2-PERNR HOTSPOT,
        35 WA2-ATTID,
        45 WA2-STATUS,
        65 WA2-REMARKS.
HIDE WA2-PERNR.
ENDLOOP.

WHEN 2.
CALL TRANSACTION 'SE11' AND SKIP FIRST SCREEN.
ENDCASE.


TOP-OF-PAGE DURING LINE-SELECTION.
CASE SY-LSIND.
WHEN 1.
    WRITE:/70 'ZPA20111 TABLE' COLOR 5.
    ULINE.
ENDCASE.
