REPORT ZSAMIKSHA_INTERACTIVE.

INCLUDE ZINTERACTIVE_TOP1.
INCLUDE ZINTERACTIVE_FORM1.

START-OF-SELECTION.
PERFORM GETDATA.
PERFORM DISPLAY.

TOP-OF-PAGE.
WRITE:/70 'MANDT' ,SY-MANDT COLOR 2,
'USER NAME', SY-UNAME COLOR 3,
'DATE',SY-DATUM COLOR 4,
'TIME', SY-UZEIT COLOR 5.
ULINE.

END-OF-PAGE.
WRITE:/70 'FOOTER' COLOR 3.
