REPORT Z_SAMIKSHA_SCRIPT.

TABLES: ZEMPLOYEE1.

SELECTION-SCREEN: BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-000.
PARAMETERS S_ID TYPE ZEMPLOYEE1-EMPID.
SELECTION-SCREEN: END OF BLOCK B2.

TYPES : BEGIN OF TY_STR,
        EMPID    TYPE ZEMPID1,
        EMPNAME  TYPE ZEMPNAME,
        LOCATION TYPE ZLOCATION,
        END OF TY_STR.

DATA: IT TYPE TABLE OF TY_STR,
      WA TYPE TY_STR.

" Data Fetching
IF S_ID IS NOT INITIAL.
  SELECT EMPID EMPNAME LOCATION
  FROM ZEMPLOYEE1
  INTO TABLE IT
  WHERE EMPID = S_ID.
ELSE.
  SELECT EMPID EMPNAME LOCATION
    FROM ZEMPLOYEE1
    INTO TABLE IT.
ENDIF.

SORT IT BY EMPID.

" Form Open Call
CALL FUNCTION 'OPEN_FORM'
  EXPORTING
    FORM     = 'ZJALAN'
    LANGUAGE = SY-LANGU.


CALL FUNCTION 'WRITE_FORM'
  EXPORTING
    ELEMENT = 'HEADER'
    WINDOW  = 'MAIN'.


LOOP AT IT INTO WA.

  ZEMPLOYEE1-EMPID    = WA-EMPID.
  ZEMPLOYEE1-EMPNAME  = WA-EMPNAME.
  ZEMPLOYEE1-LOCATION = WA-LOCATION.

  CALL FUNCTION 'WRITE_FORM'
    EXPORTING
      ELEMENT = 'ITEMDATA'
      WINDOW  = 'MAIN'.

ENDLOOP.

" Form Close Call
CALL FUNCTION 'CLOSE_FORM'.
