REPORT Z_CBS_SAMIKSHA2.

TABLES: LFA1, EKKO.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-000.
  SELECT-OPTIONS: L FOR LFA1-LIFNR.
SELECTION-SCREEN: END OF BLOCK B1 .
TYPES:
BEGIN OF TY_STR1,
LIFNR TYPE LIFNR,
NAME1 TYPE NAME1_GP,
  END OF TY_STR1.
TYPES:
BEGIN OF TY_STR2,
EBELN TYPE EBELN,
AEDAT TYPE ERDAT,
ZTERM TYPE DZTERM,
  LIFNR TYPE LIFNR,
END OF TY_STR2.

TYPES:
BEGIN OF TY_STR3,
 LIFNR TYPE LIFNR,
 NAME1 TYPE NAME1_GP,
 EBELN TYPE EBELN,
 AEDAT TYPE ERDAT,
 ZTERM TYPE DZTERM,

END OF TY_STR3.

DATA:
      IT1 TYPE TABLE OF TY_STR1,
      WA1 TYPE TY_STR1,

      IT2 TYPE TABLE OF TY_STR2,
      WA2 TYPE TY_STR2,

      IT3 TYPE TABLE OF TY_STR3,
      WA3 TYPE TY_STR3.

SELECT LIFNR NAME1
FROM LFA1 INTO TABLE IT1
WHERE LIFNR IN L .

IF IT1 IS NOT INITIAL.
  SELECT EBELN AEDAT ZTERM LIFNR
  FROM EKKO INTO TABLE IT2
  FOR ALL ENTRIES IN IT1
  WHERE LIFNR = IT1-LIFNR."COMPARING IT2 LIFNR TO IT1 LIFNR. TO AVOID DUPLICATES WE USE WHERE CONDITION.
ENDIF.

LOOP AT IT1 INTO WA1.
  MOVE: WA1-LIFNR TO WA3-LIFNR,
        WA1-NAME1 TO WA3-NAME1.

 LOOP AT IT2 INTO WA2
 WHERE LIFNR = WA1-LIFNR.

   WA3-EBELN = WA2-EBELN.
   WA3-AEDAT = WA2-AEDAT.
   WA3-ZTERM = WA2-ZTERM.
   WA3-LIFNR = WA2-LIFNR.
   APPEND WA3 TO IT3.
 ENDLOOP.
ENDLOOP.

WRITE:/ 'LIFNR' COLOR 2,
     20   'NAME1' COLOR 3,
     60   'EBELN' COLOR 4,
     80  'AEDAT' COLOR 5,
     100 'ZTERM' COLOR 6.

LOOP AT IT3 INTO WA3.
 WRITE:/ WA3-LIFNR,
      20   WA3-NAME1,
      60   WA3-EBELN,
      80   WA3-AEDAT,
      100  WA3-ZTERM.


 ENDLOOP.
